#!/usr/bin/env bash

SESSION_NAME="vscode`pwd | md5`"
KILL_SESSION=0

while getopts ":kn:" flag
do
    case $flag in
        n)
          SESSION_NAME=${OPTARG}
          ;;
        k)
          KILL_SESSION=1
          ;;
    esac
done

if [[ $KILL_SESSION -eq 1 ]]; then
  tmux kill-session -t $SESSION_NAME
else
  tmux attach-session -d -t $SESSION_NAME || tmux new-session -s $SESSION_NAME
fi
