#!/usr/bin/env bash

PWD_HASH=`pwd | md5`
SESSION_PREFIX="tls"
KILL_SESSION=0

while getopts ":kn:p:" flag
do
    case $flag in
        n)
          SESSION_NAME=${OPTARG}
          ;;
        p)
          SESSION_PREFIX=${OPTARG}
          ;;
        k)
          KILL_SESSION=1
          ;;
    esac
done

SESSION_NAME="${SESSION_NAME:="$SESSION_PREFIX$PWD_HASH"}"

if [[ $KILL_SESSION -eq 1 ]]; then
  tmux kill-session -t $SESSION_NAME
else
  tmux attach-session -d -t $SESSION_NAME || tmux new-session -s $SESSION_NAME
fi
