name: Update release on push

on:
  push:
    branches:
      - master

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/su-se-framover:${{ github.sha }}

jobs:
  generate-draft-release:
    name: Generate/update draft release
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        #with:
        # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
        # config-name: my-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
