name: Release

on:
  release:
    types: [published]

jobs:
  formula:
    name: Update Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - name: Update the Homebrew formula with latest release
        uses: NSHipster/update-homebrew-formula-action@main
        with:
          repository: ingara/tmux-lazy-session
          tap: ingara/homebrew-formulae
          formula: Formula/tmux-lazy-session.rb
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

  bottle_macos_big_sur:
    name: Build and distribute Homebrew bottle for macOS Big Sur
    runs-on: macos-10.15
    needs: [formula]
    steps:
      - name: Build a bottle using Homebrew
        run: |
          brew tap ingara/formulae
          brew install --build-bottle --verbose tmux-lazy-session
          brew bottle tmux-lazy-session
      - name: Upload the bottle to the GitHub release
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./tmux-lazy-session--${{ github.event.release.tag_name }}.big_sur.bottle.1.tar.gz
          asset_name: tmux-lazy-session-${{ github.event.release.tag_name }}.big_sur.bottle.1.tar.gz
          asset_content_type: application/gzip

  update_formula_bottle:
    name: Update the Homebrew formula again with bottle
    runs-on: ubuntu-latest
    needs:
      - bottle_macos_big_sur
    steps:
      - uses: NSHipster/update-homebrew-formula-action@main
        with:
          repository: ingara/tmux-lazy-session
          tap: ingara/homebrew-formulae
          formula: Formula/tmux-lazy-session.rb
          message: |
            Add bottles for tmux-lazy-session ${{ github.event.release.tag_name }}
            on macOS 11.0 (Big Sur)
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
